### ISSUE TITLE
v1.2: Documentation

### ISSUE THREAD

**Issue by bruce** [absinthe-graphql/absinthe#151]
This is just a reminder about some outstanding work that needs to be done on the v1.2 release.

So much documentation to update:
- [x] README, to include the feature list
- [x] `@moduledoc` and `@doc` entries
- [x] A pass through `@specs`, especially checking for old `Absinthe.Execution` types
- [x] Update to the CHANGELOG to cover outward facing changes, especially any that are breaking changes
- [x] Updates to the website repo (probably should handled in other issues)
- ~~Updates to the example Phoenix app (probably should be handled in other issues)~~ (Moving this to a separate place)

**Comment by theduke** [comment]
Highjacking this since it's open:

The mutations really need better documentation.
How do I set a custom name for a mutation?
How to handle associations?
...

Both the Tutorial/Guides and the docs on hexdoc are very light there.
